site_name: SecureSight Documentation
site_url: https://vkverma9534.github.io/SecureSight/

theme:
  name: material

nav:
  - Home: index.md
  - Project Overview: project_overview.md
  - Dataset Overview: dataset.md
  - Exploratory Data Analysis: eda.md